spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true   # ✅ JPA Hibernate 설정 안에 위치
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always

  jwt:
    issuer: ajufresh@gmail.com
    secret_key: study-springboot
